"""Strict policy parsing and deterministic managed documentation."""
import hashlib
import json
from pathlib import Path
import re
import tomllib

from .api import CheckSpec
from .files import safe_path, validate_relative

BEGIN = "<!-- aidd-gate:begin -->"
END = "<!-- aidd-gate:end -->"
NAME = re.compile(r"[A-Za-z][A-Za-z0-9_.-]{0,99}\Z")
DEFAULT_POLICY = '''version = 1
plugins = ["aidd_gate_verify", "aidd_gate_harness"]

[[checks]]
id = "syntax"
kind = "python.syntax"
paths = ["**/*.py"]

[harness]
config_files = []
rules = []
'''


def _toml_array(values: list[str]) -> str:
    """Render a list of strings using JSON's TOML-compatible string syntax."""

    return "[" + ", ".join(json.dumps(value, ensure_ascii=False) for value in values) + "]"


def python_profile_policy(
    source_roots: list[str] | None = None,
    allow_modules: list[str] | None = None,
    test_argv: list[str] | None = None,
    review_argvs: list[list[str]] | None = None,
) -> str:
    """Build the deterministic policy generated by ``init --profile python``.

    Command argv values are already shell-free tokens.  This function keeps
    generation separate from filesystem writes so CLI validation can fail
    before creating or changing repository files.
    """

    roots = list(source_roots or ["."])
    modules = list(allow_modules or [])
    reviews = list(review_argvs or [])
    if not roots or any(not isinstance(root, str) or not root for root in roots):
        raise ValueError("source roots must be non-empty relative paths")
    if not modules or any(not isinstance(module, str) or not module for module in modules):
        if allow_modules:
            raise ValueError("allow modules must be non-empty module names")
    for module in modules:
        if any(not part.isidentifier() for part in module.split(".")):
            raise ValueError("allow modules must contain dotted module names")
    source_patterns = ["**/*.py" if root == "." else f"{root.rstrip('/')}/**/*.py" for root in roots]
    syntax_paths: list[str] = []
    for pattern in source_patterns + ["tests/**/*.py"]:
        if pattern not in syntax_paths:
            syntax_paths.append(pattern)
    lines = [
        "version = 1",
        'plugins = ["aidd_gate_verify", "aidd_gate_harness"]',
        "",
        "[[checks]]",
        'id = "syntax"',
        'kind = "python.syntax"',
        f"paths = {_toml_array(syntax_paths)}",
        "",
        "[[checks]]",
        'id = "imports"',
        'kind = "python.imports"',
        f"paths = {_toml_array(source_patterns)}",
        "[checks.options]",
        f"roots = {_toml_array(roots)}",
        f"allow_modules = {_toml_array(modules)}",
        "",
        "[[checks]]",
        'id = "test-quality"',
        'kind = "python.test-quality"',
        'paths = ["tests/test_*.py"]',
    ]
    commands: list[tuple[str, list[str]]] = []
    if test_argv is not None:
        commands.append(("test-command", test_argv))
    commands.extend((f"review-{index}", argv) for index, argv in enumerate(reviews, 1))
    for check_id, argv in commands:
        lines.extend([
            "",
            "[[checks]]",
            f"id = {json.dumps(check_id)}",
            'kind = "command"',
            'paths = ["**/*.py"]',
            "[checks.options]",
            f"argv = {_toml_array(argv)}",
            "timeout = 60",
        ])
    lines.extend(["", "[harness]", "config_files = []", "rules = []", ""])
    return "\n".join(lines)


def load_policy(path: Path) -> dict:
    policy = tomllib.loads(path.read_text(encoding="utf-8"))
    if set(policy) - {"version", "plugins", "checks", "harness"}:
        raise ValueError("Unknown top-level policy key")
    if type(policy.get("version")) is not int or policy["version"] != 1:
        raise ValueError("Policy version must be 1")
    plugins = policy.get("plugins")
    if (not isinstance(plugins, list) or not plugins
            or any(not isinstance(p, str) or not NAME.fullmatch(p) for p in plugins)
            or len(set(plugins)) != len(plugins)):
        raise ValueError("plugins must be a nonempty list of unique module or entry-point names")
    checks = policy.get("checks")
    if not isinstance(checks, list) or not checks:
        raise ValueError("At least one verification check is required")
    ids: set[str] = set()
    for check in checks:
        if not isinstance(check, dict) or set(check) - {"id", "kind", "paths", "options"}:
            raise ValueError("Invalid check fields")
        for key in ("id", "kind"):
            if not isinstance(check.get(key), str) or not NAME.fullmatch(check[key]):
                raise ValueError("Each check requires valid id and kind")
        if check["id"] in ids:
            raise ValueError("Check ids must be unique")
        ids.add(check["id"])
        paths = check.get("paths", [])
        if not isinstance(paths, list):
            raise ValueError("Check paths must be an array")
        for pattern in paths:
            validate_relative(pattern)
        if not isinstance(check.get("options", {}), dict):
            raise ValueError("Check options must be a table")
    if not isinstance(policy.get("harness", {}), dict):
        raise ValueError("harness must be a table")
    return policy


def specs(policy: dict) -> list[CheckSpec]:
    return [CheckSpec(c["id"], c["kind"], tuple(c.get("paths", [])), c.get("options", {}))
            for c in policy["checks"]]


def render_agents(policy: dict) -> str:
    digest = hashlib.sha256(json.dumps(policy, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    lines = [BEGIN, "## aidd-gate policy", "", "Generated from policy. Edit the TOML, then run `aidd-gate init --sync`.",
             "Run `aidd-gate check` before merge; keep the JSON receipt as evidence.",
             "Run `aidd-gate lint-config` after changing agent configuration.", "", "Required checks:"]
    for spec in specs(policy):
        scope = ", ".join(spec.paths) or "configured command"
        lines.append(f"- `{spec.id}`: `{spec.kind}` ({scope})")
    for rule in policy.get("harness", {}).get("rules", []):
        if isinstance(rule, dict) and isinstance(rule.get("id"), str) and isinstance(rule.get("value"), str):
            lines.append(f"- Rule `{rule['id']}`: {rule['value']}")
    lines.extend(["", f"Policy SHA-256: `{digest}`", END])
    return "\n".join(lines)


def sync_agents(root: Path, policy: dict) -> None:
    path = safe_path(root, "AGENTS.md")
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    section = render_agents(policy)
    if BEGIN not in current and END not in current:
        updated = current.rstrip() + ("\n\n" if current.strip() else "") + section + "\n"
    elif current.count(BEGIN) == current.count(END) == 1 and current.index(BEGIN) < current.index(END):
        start, end = current.index(BEGIN), current.index(END) + len(END)
        updated = current[:start] + section + current[end:]
    else:
        raise ValueError("AGENTS.md has ambiguous managed section markers; repair them first")
    path.write_text(updated, encoding="utf-8")
