"""Strict policy parsing and deterministic managed documentation."""
import hashlib
import json
import os
from pathlib import Path
import re
import tomllib

from .api import CheckSpec
from .files import safe_path, validate_relative, write_atomic

BEGIN = "<!-- exitzero:begin -->"
END = "<!-- exitzero:end -->"
NAME = re.compile(r"[A-Za-z][A-Za-z0-9_.-]{0,99}\Z")
DEFAULT_POLICY = '''version = 1
plugins = ["exitzero_verify", "exitzero_harness"]

[[checks]]
id = "syntax"
kind = "python.syntax"
paths = ["**/*.py"]

[harness]
config_files = []
rules = []
'''


def _toml_array(values: list[str]) -> str:
    """Render a list of strings using JSON's TOML-compatible string syntax."""

    return "[" + ", ".join(json.dumps(value, ensure_ascii=False) for value in values) + "]"


def python_profile_policy(
    source_roots: list[str] | None = None,
    allow_modules: list[str] | None = None,
    test_argv: list[str] | None = None,
    review_argvs: list[list[str]] | None = None,
) -> str:
    """Build the deterministic policy generated by ``init --profile python``.

    Command argv values are already shell-free tokens.  This function keeps
    generation separate from filesystem writes so CLI validation can fail
    before creating or changing repository files.
    """

    roots = list(source_roots or ["."])
    modules = list(allow_modules or [])
    reviews = list(review_argvs or [])
    if not roots or any(not isinstance(root, str) or not root for root in roots):
        raise ValueError("source roots must be non-empty relative paths")
    if not modules or any(not isinstance(module, str) or not module for module in modules):
        if allow_modules:
            raise ValueError("allow modules must be non-empty module names")
    for module in modules:
        if any(not part.isidentifier() for part in module.split(".")):
            raise ValueError("allow modules must contain dotted module names")
    source_patterns = ["**/*.py" if root == "." else f"{root.rstrip('/')}/**/*.py" for root in roots]
    syntax_paths: list[str] = []
    for pattern in source_patterns + ["tests/**/*.py"]:
        if pattern not in syntax_paths:
            syntax_paths.append(pattern)
    lines = [
        "version = 1",
        'plugins = ["exitzero_verify", "exitzero_harness"]',
        "",
        "[[checks]]",
        'id = "syntax"',
        'kind = "python.syntax"',
        f"paths = {_toml_array(syntax_paths)}",
        "",
        "[[checks]]",
        'id = "imports"',
        'kind = "python.imports"',
        f"paths = {_toml_array(source_patterns)}",
        "[checks.options]",
        f"roots = {_toml_array(roots)}",
        f"allow_modules = {_toml_array(modules)}",
        "",
        "[[checks]]",
        'id = "test-quality"',
        'kind = "python.test-quality"',
        'paths = ["tests/test_*.py"]',
    ]
    commands: list[tuple[str, list[str]]] = []
    if test_argv is not None:
        commands.append(("test-command", test_argv))
    commands.extend((f"review-{index}", argv) for index, argv in enumerate(reviews, 1))
    for check_id, argv in commands:
        lines.extend([
            "",
            "[[checks]]",
            f"id = {json.dumps(check_id)}",
            'kind = "command"',
            'paths = ["**/*.py"]',
            "[checks.options]",
            f"argv = {_toml_array(argv)}",
            "timeout = 60",
        ])
    lines.extend(["", "[harness]", "config_files = []", "rules = []", ""])
    return "\n".join(lines)


def node_profile_policy(source_roots: list[str], commands: list[tuple[str, list[str]]],
                        input_paths: list[str]) -> str:
    """Connect existing Node tools; never install packages or guess their flags."""
    extensions = ("js", "jsx", "mjs", "cjs", "ts", "tsx", "mts", "cts")
    roots = list(dict.fromkeys([*source_roots, "test", "tests"]))
    paths = [f"{root.rstrip('/')}/**/*.{ext}" if root != "." else f"**/*.{ext}"
             for root in roots for ext in extensions]
    # Root tool configs are still inputs when source roots are narrowed.
    paths.extend(f"*.{ext}" for ext in extensions)
    paths.extend(f"**/{name}" for name in (
        "package.json", "package-lock.json", "npm-shrinkwrap.json", "pnpm-lock.yaml",
        "pnpm-workspace.yaml", "yarn.lock", "bun.lock", "bun.lockb", "tsconfig*.json",
        "jsconfig*.json", ".eslintrc", ".eslintrc.json", ".eslintrc.yml", ".eslintrc.yaml"))
    paths.extend(input_paths)
    paths = list(dict.fromkeys(paths))
    for pattern in paths:
        validate_relative(pattern)
    if not commands:
        raise ValueError("Node profiles require a test command")
    lines = ['version = 1', 'plugins = ["exitzero_verify", "exitzero_harness"]']
    for check_id, argv in commands:
        lines.extend(["", "[[checks]]", f"id = {json.dumps(check_id)}", 'kind = "command"',
                      'reuse = false', f"paths = {json.dumps(paths, ensure_ascii=False)}", '[checks.options]',
                      f"argv = {json.dumps(argv, ensure_ascii=False)}", 'timeout = 60'])
    lines.extend(["", "[harness]", "config_files = []", "rules = []", ""])
    return "\n".join(lines)


def load_policy(path: Path) -> dict:
    # A FIFO or device file would block the read forever; every caller
    # (run, init --sync, report) shares this single regular-file guard.
    if os.path.lexists(path) and not path.is_file():
        raise ValueError(f"Policy must be a regular file: {path.name}")
    return parse_policy(path.read_text(encoding="utf-8"))


def parse_policy(text: str) -> dict:
    """Validate policy text before a generator writes it to disk."""
    policy = tomllib.loads(text)
    if set(policy) - {"version", "plugins", "checks", "harness", "requirements"}:
        raise ValueError("Unknown top-level policy key")
    if type(policy.get("version")) is not int or policy["version"] != 1:
        raise ValueError("Policy version must be 1")
    plugins = policy.get("plugins")
    if (not isinstance(plugins, list) or not plugins
            or any(not isinstance(p, str) or not NAME.fullmatch(p) for p in plugins)
            or len(set(plugins)) != len(plugins)):
        raise ValueError("plugins must be a nonempty list of unique module or entry-point names")
    checks = policy.get("checks")
    if not isinstance(checks, list) or not checks:
        raise ValueError("At least one verification check is required")
    ids: set[str] = set()
    for check in checks:
        if not isinstance(check, dict) or set(check) - {"id", "kind", "paths", "options", "reuse", "enforcement"}:
            raise ValueError("Invalid check fields")
        for key in ("id", "kind"):
            if not isinstance(check.get(key), str) or not NAME.fullmatch(check[key]):
                raise ValueError("Each check requires valid id and kind")
        if check["id"] in ids:
            raise ValueError("Check ids must be unique")
        ids.add(check["id"])
        paths = check.get("paths", [])
        if not isinstance(paths, list):
            raise ValueError("Check paths must be an array")
        for pattern in paths:
            validate_relative(pattern)
        if not isinstance(check.get("options", {}), dict):
            raise ValueError("Check options must be a table")
        if not isinstance(check.get("reuse", True), bool):
            raise ValueError("Check reuse must be a boolean")
        if check.get("enforcement", "block") not in ("block", "warn"):
            raise ValueError("Check enforcement must be block or warn")
    if not isinstance(policy.get("harness", {}), dict):
        raise ValueError("harness must be a table")
    _validate_requirements(policy.get("requirements", []), ids)
    return policy


def _validate_requirements(requirements: object, check_ids: set[str]) -> None:
    if not isinstance(requirements, list):
        raise ValueError("requirements must be an array of tables")
    ids: set[str] = set()
    for requirement in requirements:
        if not isinstance(requirement, dict) or set(requirement) != {"id", "description", "checks"}:
            raise ValueError("Each requirement requires only id, description and checks")
        name = requirement["id"]
        if not isinstance(name, str) or not NAME.fullmatch(name) or name in ids:
            raise ValueError("Requirement ids must be valid unique names")
        ids.add(name)
        description = requirement["description"]
        if not isinstance(description, str) or not description.strip() or len(description) > 1000:
            raise ValueError("Requirement descriptions must be nonempty strings of at most 1000 characters")
        checks = requirement["checks"]
        if (not isinstance(checks, list)
                or any(not isinstance(check, str) or check not in check_ids for check in checks)
                or len(checks) != len(set(checks))):
            raise ValueError("Requirement checks must be unique existing verification check ids")


def specs(policy: dict) -> list[CheckSpec]:
    return [CheckSpec(c["id"], c["kind"], tuple(c.get("paths", [])), c.get("options", {}),
                      c.get("reuse", True), c.get("enforcement", "block"))
            for c in policy["checks"]]


def render_agents(policy: dict) -> str:
    digest = hashlib.sha256(json.dumps(policy, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    lines = [BEGIN, "## exitzero policy", "", "Generated from policy. Edit the TOML, then run `exitzero init --sync`.",
             "Run `exitzero check` before merge; keep the JSON receipt as evidence.",
             "Run `exitzero lint-config` after changing agent configuration.", "",
             "Configured checks:" if any(spec.enforcement == "warn" for spec in specs(policy)) else "Required checks:"]
    for spec in specs(policy):
        scope = ", ".join(spec.paths) or "configured command"
        note = " [warning only; violations remain recorded]" if spec.enforcement == "warn" else ""
        lines.append(f"- `{spec.id}`: `{spec.kind}` ({scope}){note}")
    for rule in policy.get("harness", {}).get("rules", []):
        if isinstance(rule, dict) and isinstance(rule.get("id"), str) and isinstance(rule.get("value"), str):
            lines.append(f"- Rule `{rule['id']}`: {rule['value']}")
    if policy.get("requirements"):
        lines.extend(["", "Completion requirement mappings (check evidence, not semantic proof):"])
        for requirement in policy["requirements"]:
            checks = ", ".join(f"`{check}`" for check in requirement["checks"]) or "unverified (no checks)"
            lines.append(f"- `{requirement['id']}` -> {checks}")
    lines.extend(["", f"Policy SHA-256: `{digest}`", END])
    return "\n".join(lines)


def updated_agents(current: str, policy: dict) -> str:
    """Prepare the managed section, preserving surrounding user guidance."""
    section = render_agents(policy)
    if BEGIN not in current and END not in current:
        updated = current.rstrip() + ("\n\n" if current.strip() else "") + section + "\n"
    elif current.count(BEGIN) == current.count(END) == 1 and current.index(BEGIN) < current.index(END):
        start, end = current.index(BEGIN), current.index(END) + len(END)
        updated = current[:start] + section + current[end:]
    else:
        raise ValueError("AGENTS.md has ambiguous managed section markers; repair them first")
    return updated


def sync_agents(root: Path, policy: dict) -> None:
    path = safe_path(root, "AGENTS.md")
    current = path.read_text(encoding="utf-8") if path.is_file() else ""
    write_atomic(path, updated_agents(current, policy))
